-- Create storage bucket for generated PDF documents
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'generated-documents',
    'generated-documents',
    false,
    10485760, -- 10MB limit
    ARRAY['application/pdf']::text[]
)
ON CONFLICT (id) DO NOTHING;

-- RLS policies for generated-documents bucket
CREATE POLICY "Users can upload their own documents"
    ON storage.objects FOR INSERT
    WITH CHECK (
        bucket_id = 'generated-documents' AND
        (storage.foldername(name))[1] = auth.uid()::text
    );

CREATE POLICY "Users can read their own documents"
    ON storage.objects FOR SELECT
    USING (
        bucket_id = 'generated-documents' AND
        (storage.foldername(name))[1] = auth.uid()::text
    );

CREATE POLICY "Users can update their own documents"
    ON storage.objects FOR UPDATE
    USING (
        bucket_id = 'generated-documents' AND
        (storage.foldername(name))[1] = auth.uid()::text
    );

CREATE POLICY "Users can delete their own documents"
    ON storage.objects FOR DELETE
    USING (
        bucket_id = 'generated-documents' AND
        (storage.foldername(name))[1] = auth.uid()::text
    );

-- Create table to track generated documents
CREATE TABLE IF NOT EXISTS public.generated_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    document_name TEXT NOT NULL,
    document_type TEXT NOT NULL,
    template_used TEXT,
    file_path TEXT NOT NULL,
    file_size BIGINT,
    storage_url TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.generated_documents ENABLE ROW LEVEL SECURITY;

-- RLS policies for generated_documents table
CREATE POLICY "Users can view their own documents"
    ON public.generated_documents FOR SELECT
    USING (user_id = auth.uid());

CREATE POLICY "Users can create their own documents"
    ON public.generated_documents FOR INSERT
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update their own documents"
    ON public.generated_documents FOR UPDATE
    USING (user_id = auth.uid());

CREATE POLICY "Users can delete their own documents"
    ON public.generated_documents FOR DELETE
    USING (user_id = auth.uid());

-- Create indexes
CREATE INDEX idx_generated_documents_user_id ON public.generated_documents(user_id);
CREATE INDEX idx_generated_documents_type ON public.generated_documents(document_type);
CREATE INDEX idx_generated_documents_created_at ON public.generated_documents(created_at DESC);

-- Add trigger for updated_at
CREATE TRIGGER update_generated_documents_updated_at
    BEFORE UPDATE ON public.generated_documents
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

COMMENT ON TABLE public.generated_documents IS 'Tracks all PDF documents generated by users with metadata and storage references';